travis:
  secure:
    BINSTAR_TOKEN: DUHqyciTSmc8NyTBW+dKGuDqz93UejUf7JLMFSBL7liMm6RiXgz77mE3AuUxFtoU42yIcYJa4yNa6Ckv2JagxmkiOlwEKtJk1Oj7I2ogC62rlNFoCE01TnAqDMllp0lMcwHVlxwFyHSg2vUrWnHiHe5Aju9cXbaUnU8ht/B9imJaGjGGW0wW8Ta2+RVU+xH8pCFrponB55dukwjrmu4o5mviP/pw90QFq5ARfmzmDLFAr2in83EY+Hcm66R7PvzRAl5WxH7BeHnBjo8Z5zxRWlKQHoUSAymSgtoBM1EYrYwDhf9o3lo6uepwlo8FKGEU8fVe6tUSwaryOEJPP20Ejin+cqLgcC/exn4a0XS55YiOvgltQEoowARUigTU8544Hzpoh9pU6us/6SjRJKlxH9Cq+4proclpvoOykMIT2xC0zk584Usj0lLSfVIpynulIz1K5Zrq/lK+wFmmFqP7nzcumjiohHBji2/TWvUok3flU4KKUD2z1U/IpOijA3JfKdiHH1+wZICwsAUFssE88Ei+gcKgvOj6fYvi4vOLKyYazPL7pJx8moPZfpyK0JFZeB0xcR60Gg08/pfUAJCpxNFZe4Skzh4J4Y28fTI/ylse2T9aiw/+SmUIbGkevOogSA4RnbfX3o3xLCS8ldAjUWLo84Afnk4WZUZB3B0iNKs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
