travis:
  secure:
    BINSTAR_TOKEN: l2IRQFPjcxUW2NCB+IpDd44cIKtE4flZWyBm9WI/IjuD5ov42DA/Kh7kUnqoCz9ZkcEHSR/mjwovCZZW3/KA9wLREC7mmDkor+N9aCz/Zm9/YelNHtp7v5FY1BnmKSEJpd5wjkrv+SkSmP77fI8kObciA3pzonfrBDxUJ3lV4KEoUuxvFmOcPujv4ejcdFeON2+FE57SSavClHLjI+BLPt25Ck29DpExa2zkYeCiRdb7kpLfShSh9A658gIWeJgwgke7rut+8ewqnF5CrxP3nBf0st2oP4+ufzJRYW30RuDKB85bU8N/Xbjq5/yMNzKnoywLMZ7EkqXZ/7uX6vcSpywbDiIlR+pTTN4d8H+R1aWmoEdhC1ZNiaTR18s8Q09dYqZpjhLqH3Gz3WdBPSvLpzKQNxRYPaxHPlpowqmuHNr3lMbWvG5JSULoprqNWEdbOP+QAq4EnMXjtv5I9R/5WWl1Maysqrhai8hhKq+uBtJCb+EMb4tXuAnrSBhXUtqgxDXCANjJbVMT7rgv25gKc46dFK4BUMVvzIt+h0LIXTkcApVtb2Rv6AXLcSkmX9d6woNqH+ZM9h7AAdP088ZVAqMTIq9SLU637655GtidSV3kpKx0qWAY1MKNbvT2wUfWNn+YBUVzqq9R13TGIWrM2RfJSKUYk04WeGM8w1RSibg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
